CREATE TABLE reading_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_filename VARCHAR(512) NOT NULL,
    pdf_content BYTEA NOT NULL,
    imported_at TIMESTAMP NOT NULL
);

CREATE TABLE reading_plan_days (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id BIGINT NOT NULL,
    day_number INT NOT NULL,
    book_name VARCHAR(256) NOT NULL,
    start_chapter INT NOT NULL,
    end_chapter INT NOT NULL,
    reading_text VARCHAR(512) NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_reading_plan_days_plan FOREIGN KEY (plan_id) REFERENCES reading_plans (id) ON DELETE CASCADE,
    CONSTRAINT uq_reading_plan_days_plan_day UNIQUE (plan_id, day_number)
);

CREATE INDEX idx_reading_plan_days_plan_id ON reading_plan_days (plan_id);
