CREATE TABLE user_reading_enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    plan_id BIGINT NOT NULL,
    plan_start_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_user_reading_enrollments_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_reading_enrollments_plan FOREIGN KEY (plan_id) REFERENCES reading_plans (id) ON DELETE CASCADE,
    CONSTRAINT uq_user_reading_enrollments_user UNIQUE (user_id)
);

CREATE TABLE user_reading_completions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id BIGINT NOT NULL,
    day_number INT NOT NULL,
    read_date DATE NOT NULL,
    CONSTRAINT fk_user_reading_completions_enrollment FOREIGN KEY (enrollment_id) REFERENCES user_reading_enrollments (id) ON DELETE CASCADE,
    CONSTRAINT uq_user_reading_completions_enrollment_day UNIQUE (enrollment_id, day_number)
);

CREATE INDEX idx_user_reading_completions_enrollment_read_date ON user_reading_completions (enrollment_id, read_date);
