CREATE TABLE user_verse_favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    version_id VARCHAR(16) NOT NULL,
    book_number INT NOT NULL,
    chapter_number INT NOT NULL,
    verse_number INT NOT NULL,
    reading_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_user_verse_favorites_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_user_verse_favorites_user_ref_date UNIQUE (user_id, version_id, book_number, chapter_number, verse_number, reading_date)
);

CREATE INDEX idx_user_verse_favorites_user_reading_date ON user_verse_favorites (user_id, reading_date);
