CREATE TABLE user_reading_segment_completions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id BIGINT NOT NULL,
    reading_plan_day_id BIGINT NOT NULL,
    segment_index INT NOT NULL DEFAULT 0,
    read_date DATE NOT NULL,
    CONSTRAINT fk_user_reading_segment_completions_enrollment FOREIGN KEY (enrollment_id) REFERENCES user_reading_enrollments (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_reading_segment_completions_plan_day FOREIGN KEY (reading_plan_day_id) REFERENCES reading_plan_days (id) ON DELETE CASCADE,
    CONSTRAINT uq_user_reading_segment_completions_enrollment_day_seg UNIQUE (enrollment_id, reading_plan_day_id, segment_index)
);

CREATE INDEX idx_user_reading_segment_completions_enrollment ON user_reading_segment_completions (enrollment_id);

/* Uma linha por reading_plan_day já concluída (dias com várias linhas no plano ficam todos marcados). */
INSERT INTO user_reading_segment_completions (enrollment_id, reading_plan_day_id, segment_index, read_date)
SELECT c.enrollment_id, rpd.id, 0, c.read_date
FROM user_reading_completions c
JOIN user_reading_enrollments e ON e.id = c.enrollment_id
JOIN reading_plan_days rpd ON rpd.plan_id = e.plan_id AND rpd.day_number = c.day_number;
